apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-jobservice
  namespace: jobbie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-jobservice
  serviceName: mysql-jobservice-headless
  template:
    metadata:
      labels:
        app: mysql-jobservice
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "jobdb"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-jobservice-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-jobservice-secret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-jobservice-secret
                  key: root-password
          volumeMounts:
            - name: job-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: job-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: job-mysql-pv-claim
 