apiVersion: v1
kind: Service
metadata:
  name: job-service-api
  namespace: jobbie-backend
spec:
  selector:
    app: job-service-api
  ports:
    - port: 8080  
      targetPort: 8080  
      name: http
  type: ClusterIP