version: "3.8"

services:
  # ---------------------------
  # JOB SERVICE MySQL
  # ---------------------------
  job_mysql:
    image: mysql:8.0
    container_name: job_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobdb
    ports:
      - "3307:3306"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  # ---------------------------
  # LISTING SERVICE MySQL
  # ---------------------------
  listing_mysql:
    image: mysql:8.0
    container_name: listing_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: jobsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - shared_net
    volumes:
      - listing_mysql_data:/var/lib/mysql
      - ./ListingService/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  # ---------------------------
  # ZOOKEEPER (shared)
  # ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------
  # KAFKA (shared)
  # ---------------------------
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------
  # JOB SERVICE API (publisher)
  # ---------------------------
  jobserviceapi:
    build:
      context: ./JobService/src
      dockerfile: ./JobService.Api/Dockerfile
    container_name: job_service_api
    ports:
      - "5000:8080"
    depends_on:
      job_mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - shared_net
    environment:
      ConnectionStrings__MySqlConnection: Server=job_mysql_db;Database=jobdb;User=root;Password=root;
      Kafka__BootstrapServers: kafka:9092
      Kafka__Topic: jobs-topic

  # ---------------------------
  # JOB SERVICE GRPC (publisher)
  # ---------------------------
  jobservicegrpc:
    build:
      context: ./JobService/src
      dockerfile: ./JobService.Grpc/Dockerfile
    container_name: job_service_grpc
    ports:
      - "5001:8080"
    depends_on:
      job_mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - shared_net
    environment:
      ConnectionStrings__MySqlConnection: Server=job_mysql_db;Database=jobdb;User=root;Password=root;
      Kafka__BootstrapServers: kafka:9092
      Kafka__Topic: jobs-topic

  # ---------------------------
  # LISTING SERVICE (consumer)
  # ---------------------------
  listingservice:
    build:
      context: ./ListingService/src
      dockerfile: Dockerfile
    container_name: listing_service
    depends_on:
      listing_mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      MYSQL_DSN: user:password@tcp(listing_mysql:3306)/jobsdb?parseTime=true
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: jobs-topic
      KAFKA_GROUP_ID: listing-service-group
    ports:
      - "8080:8080"
    networks:
      - shared_net

  # ---------------------------
  # ADMIN SERVICE API
  # ---------------------------
  adminservice:
    container_name: adminservice
    build:
      context: ./AdminService/src
      dockerfile: ./AdminService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=admin_mysql_db;Database=AdminJobDB;User=Admin;Password=Admin;"
    depends_on:
      Admindb:
        condition: service_healthy
    networks:
      - shared_net

  # ---------------------------
  # ADMIN GRPC SERVICE
  # ---------------------------
  admingrpcservice:
    container_name: admingrpcservice
    build:
      context: ./AdminService/src
      dockerfile: ./AdminGrpcService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=admin_mysql_db;Database=GrpcAdminJobDB;User=Admin;Password=Admin;"
    depends_on:
      Admindb:
        condition: service_healthy
    networks:
      - shared_net

  # ---------------------------
  # ADMIN SERVICE MySQL
  # ---------------------------
  Admindb:
    image: mysql:8.0
    container_name: admin_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: AdminJobDB
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u Admin -pAdmin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_net

volumes:
  listing_mysql_data:
  db_data:

networks:
  shared_net:
    driver: bridge
