apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobbie-backend-ingress
  namespace: jobbie-backend
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirection for HTTP (use HTTPS in prod)
  #   nginx.ingress.kubernetes.io/enable-cors: "true"
  #   nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000"
  #   nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
  #   nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"

spec:
  ingressClassName: nginx
  rules:
    - host: unolee.com
      http:
        paths:
          - path: /listing
            pathType: Prefix
            backend:
              service:
                name: listing-service
                port:
                  number: 8080
          - path: /api/Job
            pathType: Prefix
            backend:
              service:
                name: job-service-api
                port:
                  number: 8080
          - path: /api/AdminJob
            pathType: Prefix
            backend:
              service:
                name: admin-api
                port:
                  number: 8080
