apiVersion: v1
kind: ConfigMap
metadata:
  name: listing-service-config
  namespace: my-microservices
data:
  MYSQL_DSN: "user:password@tcp(listing_mysql:3306)/jobsdb?parseTime=true"
  KAFKA_BROKER: "kafka-headless:9092"
  KAFKA_TOPIC: "jobs-topic"
  KAFKA_GROUP_ID: "listing-service-group"
