apiVersion: v1
kind: ConfigMap
metadata:
  name: listing-service-config
  namespace: jobbie-backend
data:
  MYSQL_DSN: "${DB_USER}:${DB_PASSWORD}@tcp(mysql-listservice-headless:3306)/listdb?parseTime=true"
  KAFKA_BROKER: "kafka-headless:9092"
  KAFKA_TOPIC: "jobs-topic"
  KAFKA_GROUP_ID: "listing-service-group"