apiVersion: v1
kind: Secret
metadata:
  name: listing-service-secret
  namespace: jobbie-backend
type: Opaque
data:
  DB_USER: dXNlcg==            # base64(user)
  DB_PASSWORD: cGFzc3dvcmQ=    # base64(password)
