apiVersion: v1
kind: Service
metadata:
  name: job-service-grpc
  namespace: jobbie-backend
spec:
  selector:
    app: job-service-grpc
  ports:
    - port: 8080
      targetPort: 8080
      name: grpc
  type: ClusterIP