apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secret
  namespace: jobbie-backend
type: Opaque
data:
  user: dXNlcg==         # base64(user)
  password: cGFzc3dvcmQ= # base64(password)
  root-password: cm9vdA== # base64(root)