apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
  namespace: my-microservices
data:
  ConnectionStrings__MySqlConnection: "Server=job_mysql_db;Database=jobdb;User=root;Password=root;"
  Kafka__BootstrapServers: "kafka-headless:9092"
  Kafka__Topic: "jobs-topic"
