resources:
  - database/mysql-storage.yaml
  - database/secret.yaml
  - database/service.yaml
  - database/statefulset.yaml
  - job-service-api/deployment.yaml
  - job-service-api/service.yaml
  - job-service-grpc/deployment.yaml
  - job-service-grpc/service.yaml
  - configmap.yaml
  - secret.yaml
