apiVersion: v1
kind: PersistentVolume
metadata:
  name: list-mysql-pv-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/list-mysql"
  claimRef:
    name: list-mysql-pv-claim
    namespace: jobbie-backend

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: list-mysql-pv-claim
  namespace: jobbie-backend
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi