apiVersion: v1
kind: Service
metadata:
  name: mysql-listservice-headless
  namespace: jobbie-backend
spec:
  clusterIP: None
  selector:
    app: mysql-listservice
  ports:
    - port: 3306
      targetPort: 3306