apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-grpc-deployment
  namespace: jobbie-backend
  labels:
    app: admin-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-grpc
  template:
    metadata:
      labels:
        app: admin-grpc
    spec:
      containers:
        - name: admin-grpc-container
          image: jobbieregistry.azurecr.io/jobbie_adminservice_grpc:245

          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: admin-service-config
            - secretRef:
                name: admin-service-secret
      imagePullSecrets:
        - name: acr-secret
