apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-grpc-deployment
  namespace: jobbie-microservices
  labels:
    app: admin-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-grpc
  template:
    metadata:
      labels:
        app: admin-grpc
    spec:
      containers:
        - name: admin-grpc-container
          image: advanceduno/admin-grpc:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: admin-service-config
            - secretRef:
                name: admin-service-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
