name: Build and Deploy AdminService

on:
  push:
    paths:
      - 'AdminService/src/AdminService/**'

env:
  IMAGE_REPOSITORY: jobbie_adminserviceapi
  CONTAINER_REGISTRY: jobbieregistry.azurecr.io
  DOCKERFILE_PATH: AdminService/src/AdminService/Dockerfile

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: echo "tag=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_number }} \
            -f ${{ env.DOCKERFILE_PATH }} .

      - name: Save Docker image to tarball
        run: |
          docker save ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_number }} -o image.tar

      - name: Upload built image
        uses: actions/upload-artifact@v4
        with:
          name: built-image
          path: image.tar

  push:
    name: Push to ACR
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: built-image

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ needs.build.outputs.tag }}

  update-manifest:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: [push, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes Manifest
        env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
            chmod +x scripts/updateK8sManifests.sh
            ./scripts/updateK8sManifests.sh AdminService admin-api jobbie_adminserviceapi ${{ needs.build.outputs.tag }}
