name: Build and Deploy AdminService

on:
  push:
    paths:
      - 'AdminService/**'

env:
  IMAGE_REPOSITORY: jobbie_adminservice
  CONTAINER_REGISTRY: jobbieregistry.azurecr.io
  DOCKERFILE_PATH: AdminService/src/AdminGrpcService/Dockerfile
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_number }} \
            -f ${{ env.DOCKERFILE_PATH }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.run_number }}

      - name: Update Kubernetes Manifests
        run: |
          chmod +x scripts/updateK8sManifests.sh
          ./scripts/updateK8sManifests.sh AdminService ${{ env.IMAGE_REPOSITORY }} ${{ github.run_number }}
